name = "superlive-recorder"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SUPERLIVE_STATE"
id = "64750a5f7887455e88305120e1fc651f"

[triggers]
crons = ["*/5 * * * *"]
